version: 0.1.{build}

image: Ubuntu1804

install:
- sh: |
    git submodule init
    git submodule update
    sudo apt-get --assume-yes install libxdo3 libxdo-dev libx11-6 libx11-dev help2man

build_script:
- sh: |
    make package

after_build:
- sh: |
    ./mapmywindows --version
    ./mapmywindows --help

artifacts:
- path: mapmywindows.tar.gz
  name: Binary Package
- path: mapmywindows
  name: Main Binary
- path: mapmywindows.1.gz
  name: Manual Page
